name: Browser tests

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    browser-tests:
        name: "Browser tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            test-suite:  '--profile=browser --suite=connector_dall_e --config=vendor/adamwojs/connector-dall-e/behat_suites.yaml'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
